[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "acbotics_display_widgets"
version = "1.1.1"
dependencies = [
	"scipy",
	"numpy",
	"matplotlib",
	"gps",
	# "geotiff",
	# "imagecodecs",
	# "PySide2",
	"pyqtgraph",
	# "acbotics_interface",
]

[project.scripts]
run-acbotics-demo-display = "acbotics_display_widgets.scripts.acbotics_demo_display:acbotics_demo_display"
# run-acsense-logger = "acsense_display.scripts.acsense_logger:acsense_logger"
